# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-16 20:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifier', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='outletmodel',
            name='name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='outletmodel',
            name='url',
            field=models.URLField(default='https://google.com/'),
            preserve_default=False,
        ),
    ]
