# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-30 23:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifier', '0002_auto_20170416_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='outletmodel',
            name='last_checked',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='outletmodel',
            name='stock_count',
            field=models.IntegerField(null=True),
        ),
    ]
