# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-01 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifier', '0004_outletmodel_last_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outletmodel',
            name='last_checked',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='outletmodel',
            name='last_response',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='outletmodel',
            name='stock_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='outletmodel',
            name='url',
            field=models.CharField(max_length=4096),
        ),
    ]
