# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-01 17:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notifier', '0005_auto_20170501_1434'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_count', models.IntegerField()),
                ('timestamp', models.DateTimeField()),
                ('last_response', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='outletmodel',
            name='last_checked',
        ),
        migrations.RemoveField(
            model_name='outletmodel',
            name='last_response',
        ),
        migrations.RemoveField(
            model_name='outletmodel',
            name='stock_count',
        ),
        migrations.AddField(
            model_name='stockhistory',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notifier.OutletModel'),
        ),
    ]
