# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-01 17:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifier', '0006_auto_20170501_1748'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockhistory',
            old_name='last_response',
            new_name='response',
        ),
        migrations.AlterField(
            model_name='stockhistory',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
