# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 14:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notifier', '0007_auto_20170501_1753'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('email', models.EmailField(max_length=254)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notifier.OutletModel')),
            ],
        ),
    ]
