# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifier', '0009_stockhistory_sent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockhistory',
            name='sent',
        ),
        migrations.AddField(
            model_name='notificationrequest',
            name='sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
