# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifier', '0010_auto_20170502_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationrequest',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='notificationrequest',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
