# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-09 10:32
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('notifier', '0012_auto_20170506_2100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockhistory',
            name='response',
        ),
        migrations.AlterField(
            model_name='notificationrequest',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, null=True),
        ),
    ]
