# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-09 19:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifier', '0013_auto_20181009_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='outletmodel',
            name='last_checked',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
